- name: configure NodeJS Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs application
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: Add Application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create App directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download catalogue app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: install nodejs dependicies
  community.general.npm:
    path: /app
    state: latest

- name: copy catalogue.service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: start catalogue service
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: load schema
  ansible.builtin.command: mongo --host mongodb-dev.devopsroboshop.online </app/schema/${component}.js








    
