- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: app pre-req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: download golang dependencies
  ansible.builtin.shell: go mod init dispatch;go get;go build
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load